// Sample data generator for Health Timeline demonstration
import { TimelineEvent } from "@/types/medical";

export const generateSampleTimelineData = (): TimelineEvent[] => {
  return [
    {
      id: "sample-1",
      title: "Annual Physical Exam",
      date: "2024-01-15",
      metrics: {
        Systolic: 135,
        Diastolic: 85,
        Cholesterol_Total: 220,
        HDL: 45,
        LDL: 140,
        Triglycerides: 175,
        Glucose: 95,
        HbA1c: 5.8,
        Kidney_GFR: 75,
        Liver_ALT: 35,
        Liver_AST: 30,
      },
      reportName: "Annual Physical Exam.pdf",
      prescriptions: ["Lisinopril 10mg", "Atorvastatin 20mg"],
    },
    {
      id: "sample-2",
      title: "Follow-up Blood Work",
      date: "2024-03-22",
      metrics: {
        Systolic: 130,
        Diastolic: 82,
        Cholesterol_Total: 210,
        HDL: 48,
        LDL: 130,
        Triglycerides: 160,
        Glucose: 92,
        HbA1c: 5.6,
        Kidney_GFR: 78,
        Liver_ALT: 32,
        Liver_AST: 28,
        Bone_Density: "Normal",
        Vitamin_D: 32,
      },
      reportName: "Follow-up Blood Work.pdf",
      prescriptions: [
        "Lisinopril 10mg",
        "Atorvastatin 20mg",
        "Vitamin D 1000IU",
      ],
    },
    {
      id: "sample-3",
      title: "Quarterly Checkup",
      date: "2024-06-10",
      metrics: {
        Systolic: 125,
        Diastolic: 78,
        Cholesterol_Total: 195,
        HDL: 52,
        LDL: 115,
        Triglycerides: 140,
        Glucose: 88,
        HbA1c: 5.4,
        Kidney_GFR: 82,
        Liver_ALT: 28,
        Liver_AST: 25,
        Bone_Density: "Normal",
        Vitamin_D: 38,
        TSH: 2.1,
      },
      reportName: "Quarterly Checkup.pdf",
      prescriptions: [
        "Lisinopril 5mg",
        "Atorvastatin 20mg",
        "Vitamin D 1000IU",
      ],
    },
    {
      id: "sample-4",
      title: "Cardiology Consultation",
      date: "2024-09-05",
      metrics: {
        Systolic: 122,
        Diastolic: 75,
        Cholesterol_Total: 185,
        HDL: 55,
        LDL: 105,
        Triglycerides: 125,
        Glucose: 85,
        HbA1c: 5.2,
        Kidney_GFR: 85,
        Liver_ALT: 25,
        Liver_AST: 22,
        Bone_Density: "Slightly Low",
        Vitamin_D: 42,
        TSH: 1.9,
        ECG_Heart_Rate: 68,
        ECG_QT_Interval: 420,
      },
      reportName: "Cardiology Consultation.pdf",
      prescriptions: [
        "Lisinopril 5mg",
        "Atorvastatin 20mg",
        "Vitamin D 2000IU",
        "Omega-3 1000mg",
      ],
    },
    {
      id: "sample-5",
      title: "Year-End Comprehensive Panel",
      date: "2024-12-18",
      metrics: {
        Systolic: 118,
        Diastolic: 72,
        Cholesterol_Total: 175,
        HDL: 58,
        LDL: 95,
        Triglycerides: 110,
        Glucose: 82,
        HbA1c: 5.0,
        Kidney_GFR: 88,
        Liver_ALT: 22,
        Liver_AST: 20,
        Bone_Density: "Low",
        Vitamin_D: 45,
        TSH: 2.0,
        ECG_Heart_Rate: 65,
        ECG_QT_Interval: 410,
        CRP: 1.2,
        Homocysteine: 9.5,
      },
      reportName: "Year-End Comprehensive Panel.pdf",
      prescriptions: [
        "Lisinopril 5mg",
        "Atorvastatin 20mg",
        "Vitamin D 2000IU",
        "Omega-3 1000mg",
        "Folic Acid 1mg",
      ],
    },
  ];
};